describe("e2e-1 1/10/2567 at 12:20:25", () => {
  it("tests e2e-1 1/10/2567 at 12:20:25", () => {
    cy.viewport(852, 696);
    cy.visit("https://team-1849c.web.app/index.html");
    cy.get("#email").click();
    cy.get("#password").click();
    cy.get("#loginForm").click();
    cy.get("div.left-section button").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/studenthead.html?email=pakonj66%40gmail.com");
    cy.get("#userClassrooms > div:nth-of-type(1) > a").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/general.html?classroom=%E0%B8%AB%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%97%E0%B8%B3%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%81%E0%B8%A5%E0%B8%B8%E0%B9%88%E0%B8%A1&email=pakonj66%40gmail.com");
    cy.get("div.start-post > button").click();
    cy.get("#postMessage").click();
    cy.get("#postMessage").type("111");
    cy.get("#postModal button").click();
    cy.location("href").should("eq", "");
    cy.get("#documentId").click();
    cy.get("div.main-sidebar > a:nth-of-type(2)").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/Assignment.html?classroom=%E0%B8%AB%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%97%E0%B8%B3%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%81%E0%B8%A5%E0%B8%B8%E0%B9%88%E0%B8%A1&email=pakonj66%40gmail.com&documentIdl=%7B%7BdocumentId%7D%7D");
    cy.get("#pastDueTab").click();
    cy.get("#notificationMenu > i").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/Notifications.html?email=pakonj66%40gmail.com");
    cy.get("#notificationList > div:nth-of-type(1) > p").click();
    cy.get("button").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/AssignmentDetail.html?assignmentId=0WFq20TQgGGtjpwD2SAZ&email=pakonj66@gmail.com");
    cy.get("a:nth-of-type(1) > span").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/studenthead.html?email=pakonj66%40gmail.com");
    cy.get("div:nth-of-type(2) div.classroom-header").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/general.html?classroom=M101-67-%E0%B8%84%E0%B8%93%E0%B8%B4%E0%B8%95%E0%B8%A8%E0%B8%B2%E0%B8%AA%E0%B8%95%E0%B8%A3%E0%B9%8C&email=pakonj66%40gmail.com");
    cy.get("#postContainer > div:nth-of-type(1) input").click();
    cy.get("div:nth-of-type(17) input").click();
    cy.get("div:nth-of-type(17) input").type("ssssss");
    cy.get("div:nth-of-type(17) > div.comment-section > button").click();
    cy.location("href").should("eq", "");
    cy.get("div:nth-of-type(17) > button").click();
    cy.get("div.start-post > button").click();
    cy.get("#postMessage").click();
    cy.get("#postMessage").type("11");
    cy.get("#postModal button").click();
    cy.location("href").should("eq", "");
    cy.get("div:nth-of-type(18) > div.post-header i").click();
    cy.get("div:nth-of-type(18) a").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/general.html?classroom=M101-67-%E0%B8%84%E0%B8%93%E0%B8%B4%E0%B8%95%E0%B8%A8%E0%B8%B2%E0%B8%AA%E0%B8%95%E0%B8%A3%E0%B9%8C&email=pakonj66%40gmail.com#");
    cy.get("div.content-header a").click();
    cy.get("#postContainer > div:nth-of-type(1) a").click();
    cy.get("a:nth-of-type(1) > span").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/studenthead.html?email=pakonj66%40gmail.com&classroom=M101-67-%E0%B8%84%E0%B8%93%E0%B8%B4%E0%B8%95%E0%B8%A8%E0%B8%B2%E0%B8%AA%E0%B8%95%E0%B8%A3%E0%B9%8C");
    cy.get("div.user-section i").click();
    cy.get("#logoutLink").click();
    cy.location("href").should("eq", "https://team-1849c.web.app/index.html");
  });
});
